To implement arrays creation routines and implement the basic operations using NumPy.

In [ ]:
import numpy as np

In [41]:
# Create 1D Array and operations on this

In [31]:
a = np.array([8,7,6,5,4,3,2,1,0])
a

array([8, 7, 6, 5, 4, 3, 2, 1, 0])

In [32]:
b = np.array([1,2,3,4,5,6,7])
b

array([1, 2, 3, 4, 5, 6, 7])

In [33]:
print('Shape: ', b.shape)
print('Datatype: ', b.dtype)
print('Size: ', b.size)
print('Num Dimensions: ', b.ndim)

Shape:  (7,)
Datatype:  int32
Size:  7
Num Dimensions:  1


In [9]:
c = np.arange(10)
c

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
d = np.arange(1, 10, 2)
d

array([1, 3, 5, 7, 9])

In [ ]:
# Arithmetic Operations on array

In [25]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [27]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [26]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [39]:
arr + 10

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [40]:
arr ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [ ]:
# Create a 2d array

In [16]:
list2 = [[1, 2, 3, 4],[3, 4, 5, 6], [5, 6, 7, 8]]
list2

[[1, 2, 3, 4], [3, 4, 5, 6], [5, 6, 7, 8]]

In [18]:
arr2 = np.array(list2)
arr2

array([[1, 2, 3, 4],
       [3, 4, 5, 6],
       [5, 6, 7, 8]])

In [19]:
print('Shape: ', arr2.shape)
print('Datatype: ', arr2.dtype)
print('Size: ', arr2.size)
print('Num Dimensions: ', arr2.ndim)

Shape:  (3, 4)
Datatype:  int32
Size:  12
Num Dimensions:  2


In [34]:
print("Mean value is: ", arr2.mean())
print("Max value is: ", arr2.max())
print("Min value is: ", arr2.min())

Mean value is:  4.5
Max value is:  8
Min value is:  1
